# Generated by Django 5.0.2 on 2024-03-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_thumbnail'),
        ('blog', '0004_post_like'),
    ]

    operations = [
    ]
