# Generated by Django 5.0.2 on 2024-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('new_post', 'Нова пошта'), ('ukr_post', 'Укрпошта'), ('pickup', 'Самовивіз'), ('courier', "Кур'єрська доставка")], max_length=50),
        ),
    ]
